#!/usr/bin/env python3
"""
Sync the clean five-letter list from backend → frontend.

Run from repo root:
    python jumbles/scripts/refresh_words.py --frontend ./jumbles-frontend
"""

from pathlib import Path
import argparse, shutil, textwrap

# ── CLI ────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument("--frontend", required=True, type=Path,
                    help="Path to jumbles-frontend repo root")
args = parser.parse_args()

# ── Paths ──────────────────────────────────────────────────────────
BACKEND_ROOT   = Path(__file__).resolve().parent.parent      # jumbles/
CLEAN_TXT_SRC  = BACKEND_ROOT / "data" / "words5_clean.txt"        # already cleaned
FRONTEND_ROOT  = args.frontend.resolve()
TXT_DEST_DIR   = FRONTEND_ROOT / "data"
TS_DEST_FILE   = FRONTEND_ROOT / "src" / "words5.ts"

# ── Copy .txt into frontend/data/ ─────────────────────────────────
TXT_DEST_DIR.mkdir(parents=True, exist_ok=True)
shutil.copy2(CLEAN_TXT_SRC, TXT_DEST_DIR / "words5.txt")

# ── Build the TS array in frontend/src/ ───────────────────────────
words = [w.strip() for w in (CLEAN_TXT_SRC).read_text().splitlines()]

ts_code = textwrap.dedent(f"""\
    // Auto-generated by refresh_words.py – DO NOT EDIT
    export const WORDS = [
    {',\n'.join('  "' + w + '"' for w in words)}
    ] as const;
""")
TS_DEST_FILE.write_text(ts_code)

print("✅  Synced list:")
print(f"    • {TXT_DEST_DIR / 'words5.txt'}")
print(f"    • {TS_DEST_FILE}")
